export const cityOptions = [
  { value: 'alaminos', label: 'Alaminos' },
  { value: 'angeles', label: 'Angeles' },
  { value: 'antipolo', label: 'Antipolo' },
  { value: 'bacoor', label: 'Bacoor' },
  { value: 'baguio', label: 'Baguio' },
  { value: 'bais', label: 'Bais' },
  { value: 'balanga', label: 'Balanga' },
  { value: 'bayawan', label: 'Bayawan' },
  { value: 'bayugan', label: 'Bayugan' },
  { value: 'bislig', label: 'Bislig' },
  { value: 'binan', label: 'Biñan' },
  { value: 'batac', label: 'Batac' },
  { value: 'batangas-city', label: 'Batangas City' },
  { value: 'cabanatuan', label: 'Cabanatuan' },
  { value: 'cabadbaran', label: 'Cabadbaran' },
  { value: 'cagayan-de-oro', label: 'Cagayan de Oro' },
  { value: 'cadiz', label: 'Cadiz' },
  { value: 'calamba', label: 'Calamba' },
  { value: 'calapan', label: 'Calapan' },
  { value: 'cavite-city', label: 'Cavite City' },
  { value: 'cotabato-city', label: 'Cotabato City' },
  { value: 'dagupan', label: 'Dagupan' },
  { value: 'danao', label: 'Danao' },
  { value: 'dapitan', label: 'Dapitan' },
  { value: 'dasmarinas', label: 'Dasmariñas' },
  { value: 'davao', label: 'Davao City' },
  { value: 'digos', label: 'Digos' },
  { value: 'dipolog', label: 'Dipolog' },
  { value: 'dumaguete', label: 'Dumaguete' },
  { value: 'el-salvador', label: 'El Salvador' },
  { value: 'escalante', label: 'Escalante' },
  { value: 'gapan', label: 'Gapan' },
  { value: 'general-santos', label: 'General Santos' },
  { value: 'general-trias', label: 'General Trias' },
  { value: 'gingoog', label: 'Gingoog' },
  { value: 'ilagan', label: 'Ilagan' },
  { value: 'iligan', label: 'Iligan' },
  { value: 'iloilo', label: 'Iloilo City' },
  { value: 'imus', label: 'Imus' },
  { value: 'iriga', label: 'Iriga' },
  { value: 'isabela', label: 'Isabela City' },
  { value: 'kabankalan', label: 'Kabankalan' },
  { value: 'kidapawan', label: 'Kidapawan' },
  { value: 'koronadal', label: 'Koronadal' },
  { value: 'la-carlota', label: 'La Carlota' },
  { value: 'laoag', label: 'Laoag' },
  { value: 'lamitan', label: 'Lamitan' },
  { value: 'las-pinas', label: 'Las Piñas' },
  { value: 'ligao', label: 'Ligao' },
  { value: 'lipa', label: 'Lipa' },
  { value: 'lucena', label: 'Lucena' },
  { value: 'maasin', label: 'Maasin' },
  { value: 'makati', label: 'Makati' },
  { value: 'malabon', label: 'Malabon' },
  { value: 'malaybalay', label: 'Malaybalay' },
  { value: 'malolos', label: 'Malolos' },
  { value: 'mandaluyong', label: 'Mandaluyong' },
  { value: 'mandaue', label: 'Mandaue' },
  { value: 'manila', label: 'Manila' },
  { value: 'marawi', label: 'Marawi' },
  { value: 'marikina', label: 'Marikina' },
  { value: 'masbate-city', label: 'Masbate City' },
  { value: 'mati', label: 'Mati' },
  { value: 'meycauayan', label: 'Meycauayan' },
  { value: 'munoz', label: 'Muñoz' },
  { value: 'muntinlupa', label: 'Muntinlupa' },
  { value: 'naga-camarines-sur', label: 'Naga (Camarines Sur)' },
  { value: 'naga-cebu', label: 'Naga (Cebu)' },
  { value: 'navotas', label: 'Navotas' },
  { value: 'olongapo', label: 'Olongapo' },
  { value: 'ormoc', label: 'Ormoc' },
  { value: 'oroquieta', label: 'Oroquieta' },
  { value: 'ozamis', label: 'Ozamiz' },
  { value: 'pagadian', label: 'Pagadian' },
  { value: 'palayan', label: 'Palayan' },
  { value: 'panabo', label: 'Panabo' },
  { value: 'paranaque', label: 'Parañaque' },
  { value: 'pasay', label: 'Pasay' },
  { value: 'pasig', label: 'Pasig' },
  { value: 'passi', label: 'Passi' },
  { value: 'puerto-princesa', label: 'Puerto Princesa' },
  { value: 'quezon', label: 'Quezon City' },
  { value: 'roxas', label: 'Roxas' },
  { value: 'sagay', label: 'Sagay' },
  { value: 'samal', label: 'Samal' },
  { value: 'san-carlos-negros-occidental', label: 'San Carlos (Negros Occidental)' },
  { value: 'san-carlos-pangasinan', label: 'San Carlos (Pangasinan)' },
  { value: 'san-fernando-la-union', label: 'San Fernando (La Union)' },
  { value: 'san-fernando-pampanga', label: 'San Fernando (Pampanga)' },
  { value: 'san-jose', label: 'San Jose' },
  { value: 'san-jose-del-monte', label: 'San Jose del Monte' },
  { value: 'san-juan', label: 'San Juan' },
  { value: 'san-pablo', label: 'San Pablo' },
  { value: 'san-pedro', label: 'San Pedro' },
  { value: 'santa-rosa', label: 'Santa Rosa' },
  { value: 'santiago', label: 'Santiago' },
  { value: 'silay', label: 'Silay' },
  { value: 'sipalay', label: 'Sipalay' },
  { value: 'sorsogon-city', label: 'Sorsogon City' },
  { value: 'surigao-city', label: 'Surigao City' },
  { value: 'tabaco', label: 'Tabaco' },
  { value: 'tagaytay', label: 'Tagaytay' },
  { value: 'tagbilaran', label: 'Tagbilaran' },
  { value: 'taguig', label: 'Taguig' },
  { value: 'tagum', label: 'Tagum' },
  { value: 'talisay-cebu', label: 'Talisay (Cebu)' },
  { value: 'talisay-negros-occidental', label: 'Talisay (Negros Occidental)' },
  { value: 'tanauan', label: 'Tanauan' },
  { value: 'tandag', label: 'Tandag' },
  { value: 'tangub', label: 'Tangub' },
  { value: 'tarlac', label: 'Tarlac' },
  { value: 'tayabas', label: 'Tayabas' },
  { value: 'toledo', label: 'Toledo' },
  { value: 'trece-martires', label: 'Trece Martires' },
  { value: 'tuguegarao', label: 'Tuguegarao' },
  { value: 'urdaneta', label: 'Urdaneta' },
  { value: 'valencia', label: 'Valencia' },
  { value: 'valenzuela', label: 'Valenzuela' },
  { value: 'victorias', label: 'Victorias' },
  { value: 'vigan', label: 'Vigan' },
  { value: 'zamboanga', label: 'Zamboanga City' }]